In [1]:
from rbm import RBM

In [3]:
import numpy as np

In [4]:
rbm = RBM(num_visible=6, num_hidden=2)

In [5]:
base = np.array([[1, 1, 1, 0, 0, 0], 
                 [1, 0, 1, 0, 0, 0],
                [1, 1, 0, 1, 0, 1]])

In [7]:
rbm.train(base, max_epochs=5000)

Epoch 0: error is 4.532177102712966
Epoch 1: error is 4.464244396959427
Epoch 2: error is 4.306905045469398
Epoch 3: error is 4.198659727781648
Epoch 4: error is 4.197358698035941
Epoch 5: error is 4.082902950467508
Epoch 6: error is 3.7174396319063012
Epoch 7: error is 3.7617090388968357
Epoch 8: error is 3.5232879937303427
Epoch 9: error is 3.7509916861836254
Epoch 10: error is 3.526979513736477
Epoch 11: error is 3.3496070673660587
Epoch 12: error is 3.3860910720862467
Epoch 13: error is 3.6876795630900325
Epoch 14: error is 3.385817508589053
Epoch 15: error is 3.08240943299963
Epoch 16: error is 3.0352726207697187
Epoch 17: error is 3.0931865462719976
Epoch 18: error is 3.2290700213749206
Epoch 19: error is 3.1925214304537355
Epoch 20: error is 3.0976458278034
Epoch 21: error is 2.891219793417533
Epoch 22: error is 3.1157735738772567
Epoch 23: error is 2.87688391975753
Epoch 24: error is 2.9631721964430096
Epoch 25: error is 3.0200476801544234
Epoch 26: error is 3.0754987671284635


In [8]:
rbm.weights

array([[ 2.15423119,  0.89590705, -1.23136536],
       [ 5.04730942,  2.28817208,  1.04535607],
       [ 0.16583498, -4.04572824,  8.34641252],
       [-0.42076259,  8.78062834, -3.76701248],
       [ 1.81204032, -8.73372163,  2.39366219],
       [-3.87971395, -2.29437874, -2.58423135],
       [ 1.83345912, -8.7363956 ,  2.37293712]])

In [9]:
import pandas as pd
pd.DataFrame(rbm.weights)

0         1         2
0  2.154231  0.895907 -1.231365
1  5.047309  2.288172  1.045356
2  0.165835 -4.045728  8.346413
3 -0.420763  8.780628 -3.767012
4  1.812040 -8.733722  2.393662
5 -3.879714 -2.294379 -2.584231
6  1.833459 -8.736396  2.372937

In [10]:
df = pd.DataFrame(base)
df

0  1  2  3  4  5
0  1  1  1  0  0  0
1  1  0  1  0  0  0
2  1  1  0  1  0  1

In [14]:
usuario1 = np.array([[1, 1, 0, 1, 0, 0]])
rbm.run_visible(usuario1)

array([[0., 1.]])

In [15]:
user2 = np.array([[0, 0, 0, 1, 1, 0]])
rbm.run_visible(user2)

array([[0., 0.]])

In [35]:
camada = np.array([[0, 1]])
recomen = rbm.run_hidden(camada)

In [36]:
recomen

array([[1., 1., 0., 1., 0., 1.]])

In [37]:
filmes = ["A bruxa", "Invocação do Mal", "O chamado", "Se beber não case", "Gente Grande", "American Pie"]

In [38]:
for i in range(len(user2[0])):
    #print(usuario1[0, i])
    if user2[0, i] == 0 and recomen[0, i] == 1:
        print(filmes[i])

A bruxa
Invocação do Mal
American Pie
